name: 'Git Cleanup'
description: 'delete old branches and PRs from repo'
inputs:
  numDays:
    description: 'Number of days after which branches are deleted'
    required: false
    default: '180'
  numTags:
    description: 'Number of tags to be kept (sorted by tag date) pass 0 to delete all tags'
    required: false
    default: '5'
outputs:
  branches:
    description: 'The branches picked up by the action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.numDays }}
    - ${{ inputs.numTags }}