name: 'Git Cleanup'
description: 'delete old branches and PRs from repo'
inputs:
  numDays:
    description: 'Number of days after which branches are deleted'
    required: false
    default: '180'
  numTags:
    description: 'Number of tags to be kept (sorted by tag date) pass 0 to delete all tags'
    required: false
    default: '5'
  skipTags:
    description: 'Tag prefix to skip deleting (e.g. "v" to keep version tags)'
    required: false
    default: ''
  dryRun:
    description: 'Dry run - do not delete anything'
    required: false
    type: boolean
    default: true
outputs:
  branches:
    description: 'The branches picked up by the action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.numDays }}
    - ${{ inputs.numTags }}
    - ${{ inputs.skipTags }}
    - ${{ inputs.dryRun }}